### ISSUE TITLE
(1) ¿Que es unacomunicacion REST?, Para que se usan?, Ejemplifique.

### ISSUE THREAD

**Issue by guelo2019** [ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea4-grupo-7#1]

**Comment by recursosssbb** [comment]
[tarea1-ejercicio1-grupo7.pdf](https://github.com/ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea4-grupo-7/files/11453650/tarea1-ejercicio1-grupo7.pdf)
